import config from 'config'

const literals = {
  en: {
    AcceptedAt: 'Accepted at',
    Account: 'Account',
    AccountId: 'Account ID',
    AccountsCount: 'Accounts count',
    Address: 'Address',
    AddressesCount: 'Addresses count',
    ChildDevicesCount: 'Child devices count',
    CitiesCount: 'Cities count',
    City: 'City',
    Code: 'Code',
    Complex: 'Complex',
    Configuration: 'Configuration',
    ConfigurationSuccessfullyUpdated: 'Device configuration successfully updated',
    ConfigurationUpdateKitFailed: 'Error applying configuration update kit',
    Country: 'Country',
    Customer: 'Customer',
    CustomerId: 'Customer ID',
    CustomersCount: 'Customers count',
    Days: 'days',
    Description: 'Description',
    Details: 'Details',
    Device: 'Device',
    DeviceNotInitialized: 'The device has not yet passed the initialization in the system',
    Devices: 'Devices',
    DevicesCount: 'Devices count',
    DisplayedNodeTypes: 'Displayed node types',
    Error: 'Error',
    Errors: 'Errors',
    Events: 'Events',
    EventsCount: 'Events count',
    FileAlreadyUploadedToDevice: 'File already uploaded to device',
    FileApplyError: 'File apply error',
    FileCrcDoesNotMatch: 'File error - CRC does not match',
    FileDeleteError: 'File delete error',
    FileDownloading: 'File downloading',
    FileLoadingMessage: (downloaded, size, percent) =>
      `Downloaded ${downloaded} of ${size} bytes (${percent}%) ...`,
    FileMissing: 'File missing',
    FileSaveFailed: 'File save failed',
    FilterByConnectedDevices: 'Filter by connected devices',
    Find: 'Find',
    HasNotActualInformationAboutDevice: 'There is no current information about the terminal status',
    IdleDevices: 'Idle devices',
    Loading: 'Loading',
    LogicalDevice: 'Logical device',
    Merchant: 'Merchant',
    MerchantId: 'Merchant ID',
    MerchantsCount: 'Merchants count',
    MessageEmitter: 'Message emitter',
    Model: 'Model',
    NoConfiguration: 'No configuration',
    NoKey: 'No key',
    NoSoftware: 'No software',
    NoSslCert: 'No SSL certificate',
    PackageLoadingMessage: (downloaded, count, name) =>
      `Downloading ${downloaded} / ${count} file "${name}" ...`,
    PhysicalDevice: 'Physical device',
    Region: 'Region',
    RegionCode: 'Region code',
    RegionsCount: 'Regions count',
    ResetFilters: 'Reset filters',
    Resolve: 'RESOLVE',
    ScriptHasBeenLoaded: 'Script has been loaded',
    SerialNumber: 'Serial Number',
    Software: 'Software',
    SoftwareUpdateKitFailed: 'Error applying software update kit',
    SoftwareSuccessfullyUpdated: 'Device software successfully updated',
    SslCertApplyFailed: 'Error applying SSL certificate',
    Status: 'Status',
    StatusOfWork: 'Status of work',
    TaskScriptFound: 'Task script found',
    Terminal: 'Terminal',
    TerminalId: 'Terminal ID',
    TerminalIdCount: 'Terminal ID count',
    ThereAreNoConfigUpdateTasks: 'There are no configuration update tasks',
    ThereAreNoSoftwareUpdateTasks: 'There are no software update tasks',
    ThereIsNoPrinterPaper: 'There is no printer paper',
    TimeSinceLastRequest: 'Time since last request',
    TradePoint: 'Trade point',
    TradePointsCount: 'Trade points count',
    Type: 'Type',
    Unknown: 'Unknown',
    UnknownError: 'Unknown error',
    UnknownEvent: 'Unknown event',
    UnknownNodeType: 'Unknown node type',
    UnknownWarning: 'Unknown warning',
    UpdateKitDownloaded: 'Update kit downloaded',
    UpdateKitSuccessfullyApplied: 'Update kit successfully applied',
    UnknownImmediatelyFlag: 'Unknown Immediately flag for applying the downloaded file',
    UnknownTypeOfAction: 'Unknown type of Action',
    UnknownTypeOfFileBeingTransferred: 'Unknown type of file being transferred',
    Warning: 'Warning'
  },
  ru: {
    AcceptedAt: 'Принято',
    Account: 'Счет клиента',
    AccountId: 'Идентификатор счета клиента',
    AccountsCount: 'Количество счетов клиента',
    Address: 'Адрес',
    AddressesCount: 'Количество адресов',
    ChildDevicesCount: 'Количество дочерних устройств',
    CitiesCount: 'Количество городов',
    City: 'Город',
    Code: 'Код',
    Complex: 'Комплекс',
    Configuration: 'Конфигурация',
    ConfigurationSuccessfullyUpdated: 'конфигурация устройства успешно обновлена',
    ConfigurationUpdateKitFailed: 'Ошибка применения пакета обновления конфигурации',
    Country: 'Страна',
    Customer: 'Кастомер',
    CustomerId: 'Идентификатор кастомера',
    CustomersCount: 'Количество кастомеров',
    Days: 'дней',
    Description: 'Описание',
    Details: 'Подробнее',
    Device: 'Устройство',
    DeviceNotInitialized: 'Устройство еще не прошло первичную инициализуцию в системе',
    Devices: 'Устройства',
    DevicesCount: 'Количество устройств',
    DisplayedNodeTypes: 'Отображаемые типы узлов',
    Error: 'Ошибка',
    Errors: 'Ошибки',
    Events: 'События',
    EventsCount: 'Количество событий',
    FileAlreadyUploadedToDevice: 'Файл уже загружен в устройство',
    FileApplyError: 'Ошибка применения файла',
    FileCrcDoesNotMatch: 'Ошибка файла — не совпадает CRC',
    FileDeleteError: 'Ошибка удаления файла',
    FileDownloading: 'Загрузка файла',
    FileLoadingMessage: (downloaded, size, percent) =>
      `Загружено ${downloaded} из ${size} байт (${percent}%) ...`,
    FileMissing: 'Файл отсутствует',
    FilterByConnectedDevices: 'Фильтр по связанным устройствам',
    Find: 'Искать',
    HasNotActualInformationAboutDevice: 'Отсутствует актуальная информация о статусе терминала',
    IdleDevices: 'Простаивающих устройств',
    Loading: 'Загрузка',
    LogicalDevice: 'Логическое устройство',
    Merchant: 'Мерчант',
    MerchantId: 'Идентификатор мерчанта',
    MerchantsCount: 'Количество мерчантов',
    MessageEmitter: 'Отправитель сообщения',
    Model: 'Модель',
    NoConfiguration: 'Отсутствует конфигурация',
    NoKey: 'Отсутствует ключ',
    NoSoftware: 'Отсутствует программное обеспечение',
    NoSslCert: 'Отсутствует SSL сертификат',
    PackageLoadingMessage: (downloaded, count, name) =>
      `Загружается ${downloaded} / ${count} файл "${name}" ...`,
    PhysicalDevice: 'Физическое устройство',
    Region: 'Регион',
    RegionCode: 'Код региона',
    RegionsCount: 'Количество регионов',
    ResetFilters: 'Сбросить фильтры',
    Resolve: 'РЕШЕНО',
    ScriptHasBeenLoaded: 'Скрипт был загружен',
    SerialNumber: 'Серийный номер',
    Software: 'Программное обеспечение',
    SoftwareUpdateKitFailed: 'Ошибка применения пакета обновления ПО',
    SoftwareSuccessfullyUpdated: 'программное обеспечение устройства успешно обновлено',
    SslCertApplyFailed: 'Ошибка применения SSL сертификата',
    Status: 'Статус',
    StatusOfWork: 'Статус работы',
    TaskScriptFound: 'Обнаружен скрипт задания',
    Terminal: 'Терминал',
    TerminalId: 'Terminal ID',
    TerminalIdCount: 'Количество Terminal ID',
    ThereAreNoConfigUpdateTasks: 'Задание на обновление конфигурации отсутствует',
    ThereAreNoSoftwareUpdateTasks: 'Задание на обновление ПО отсутствует',
    ThereIsNoPrinterPaper: 'Отсутствует бумага для принтера',
    TimeSinceLastRequest: 'Время с последнего запроса',
    TradePoint: 'Торговая точка',
    TradePointsCount: 'Количество торговых точек',
    Type: 'Тип',
    Unknown: 'Неизвестно',
    UnknownError: 'Неизвестная ошибка',
    UnknownEvent: 'Unknown event',
    UnknownNodeType: 'Неизвестный тип узла',
    UnknownWarning: 'Неизвестное предупреждение',
    UpdateKitDownloaded: 'Комплект обновлений загружен',
    UpdateKitSuccessfullyApplied: 'Пакет обновления успешно применен',
    UnknownImmediatelyFlag: 'Неизвестный флаг применения загруженного файла Immediately',
    UnknownTypeOfAction: 'Неизвестный тип Action',
    UnknownTypeOfFileBeingTransferred: 'Неизвестный тип передаваемого файла',
    Warning: 'Предупреждение'
  }
}

const Localization = literals[config.lang]

export default Localization
